version: '3'

x-dev-base: &dev-base
  build: .
  environment:
    DB_HOST: mysql01
    DB_PORT: 3306
    DB_USERNAME: scott
    DB_PASSWORD: tiger
    DB_NAME: nestjs_learn
    SERVER_APOLLO_URI: http://backend:3300
    PUBLIC_APOLLO_URI: http://localhost:3300
  volumes:
    - .:/app
    - /app/node_modules
    - /app/packages/backend/node_modules
    - /app/packages/frontend/node_modules

services:
  mysql:
    image: mysql:latest
    container_name: mysql01
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_learn
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
      - './docker/mysql/conf:/etc/mysql/conf.d'
      - './docker/mysql/initdb:/docker-entrypoint-initdb.d'
    ports:
      - 3306:3306

  # migrate:
  #   << : *dev-base
  #   working_dir: /app/packages/backend
  #   command: yarn migrate:deploy
  #   depends_on:
  #     - mysql
  backend:
    <<: *dev-base
    working_dir: /app/packages/backend
    command: yarn start:dev
    tty: true
    depends_on:
      - mysql
      # - migrate
    ports:
      - '3300:3300'

  frontend:
    <<: *dev-base
    working_dir: /app/packages/frontend
    command: yarn dev
    depends_on:
      - backend
    ports:
      - '3000:3000'
