version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql01
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_learn
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - '/docker/mysql/data:/var/lib/mysql'
      - '/docker/mysql/conf:/etc/mysql/conf.d'
      - '/docker/mysql/initdb:/docker-entrypoint-initdb.d'
    ports:
      - 3306:3306
